networks:
  hs-room:
    driver: bridge

services:

  
  hs-room-backend-api:
    image: hs-room-backend-api
    container_name: hs-room-backend-api
    restart: always
    build:
      context: ./backend/api
    env_file: ./.env
    ports:
      - 4000:4000
    networks:
      - hs-room

    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:4000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  hs-room-frontend-home:
    container_name: hs-room-frontend-home
    build:
      context: ./frontend/home
      dockerfile: Dockerfile
      
    ports:
      - 3000:3000
    networks:
      - hs-room
    env_file:
      - ./.env

  